### ISSUE TITLE
Blind Saves

### ISSUE THREAD

**Issue by apoapostolov** [MatrixWizard/tsamys-secret-rolls-pf2e#2]
Mainly useful for blinding Fortitude saves, especially during poisons and onsets on diseases.

**Comment by MatrixWizard** [comment]
I have updated the module to support this, Fortitude, Reflex & Will saves on PF2e and Death Saves on D&D5e

If you have any other suggestions feel free to let me know :D

**Comment by apoapostolov** [comment]
Thank you so much!
